"""Export service — generates PDF, CSV, JSON, and HL7 FHIR exports."""

from __future__ import annotations

import csv
import io
import json
import logging
import os
import tempfile
import uuid
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Template
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.coding_result import CodingResult
from app.models.coding_session import CodingSession
from app.models.export import Export
from app.models.patient import Patient
from app.schemas.export import ExportFormat

logger = logging.getLogger(__name__)

_EXPORT_DIR = Path(tempfile.gettempdir()) / "autocode_exports"

_PDF_TEMPLATE = """\
<html>
<head>
<style>
  body { font-family: Arial, sans-serif; margin: 40px; font-size: 12px; }
  h1 { color: #1a365d; font-size: 20px; border-bottom: 2px solid #1a365d; padding-bottom: 8px; }
  h2 { color: #2d3748; font-size: 16px; margin-top: 24px; }
  .header-box { border: 1px solid #ccc; padding: 12px; margin-bottom: 20px;
                 background: #f7fafc; border-radius: 4px; }
  .header-box p { margin: 4px 0; }
  .label { font-weight: bold; display: inline-block; width: 160px; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; }
  th { background: #2d3748; color: #fff; padding: 8px; text-align: left; font-size: 11px; }
  td { padding: 8px; border-bottom: 1px solid #e2e8f0; font-size: 11px; }
  tr:nth-child(even) { background: #f7fafc; }
  .validated { color: #276749; }
  .unvalidated { color: #9b2c2c; }
  .notes { background: #fffff0; padding: 12px; border-left: 3px solid #d69e2e;
            margin-top: 16px; white-space: pre-wrap; }
  .footer { margin-top: 30px; font-size: 10px; color: #718096;
            border-top: 1px solid #e2e8f0; padding-top: 8px; }
</style>
</head>
<body>
  <h1>Medical Coding Report</h1>
  <div class="header-box">
    {% if patient %}
    <p><span class="label">Patient Name:</span>{{ patient.first_name }} {{ patient.last_name }}</p>
    <p><span class="label">Date of Birth:</span>{{ patient.date_of_birth or 'N/A' }}</p>
    <p><span class="label">MRN:</span>{{ patient.mrn }}</p>
    <p><span class="label">Gender:</span>{{ patient.gender or 'N/A' }}</p>
    {% endif %}
    <p><span class="label">Session ID:</span>{{ session.id }}</p>
    <p><span class="label">Date:</span>{{ session.created_at.strftime('%Y-%m-%d %H:%M UTC') }}</p>
    <p><span class="label">Standard:</span>ICD-10-CM 2026</p>
    <p><span class="label">LLM Provider:</span>{{ session.llm_provider }} / {{ session.llm_model }}</p>
    <p><span class="label">Status:</span>{{ session.status }}</p>
  </div>

  {% if include_clinical_notes %}
  <h2>Clinical Notes</h2>
  <div class="notes">{{ session.clinical_input }}</div>
  {% endif %}

  <h2>Coding Results</h2>
  <table>
    <tr>
      <th>#</th>
      <th>Code</th>
      <th>Description</th>
      <th>Confidence</th>
      <th>Validated</th>
      {% if include_reasoning %}<th>Rationale</th>{% endif %}
    </tr>
    {% for r in results %}
    <tr>
      <td>{{ r.sequence_order + 1 }}</td>
      <td><strong>{{ r.icd_code }}</strong></td>
      <td>{{ r.icd_description }}</td>
      <td>{{ '%.0f%%' | format(r.confidence_score * 100) }}</td>
      <td class="{{ 'validated' if r.is_validated else 'unvalidated' }}">
        {{ 'Yes' if r.is_validated else 'No' }}
      </td>
      {% if include_reasoning %}<td>{{ r.rationale or '' }}</td>{% endif %}
    </tr>
    {% endfor %}
  </table>

  <div class="footer">
    <p>Generated by Auto Code on {{ export_date }} | Session {{ session.id }}</p>
  </div>
</body>
</html>
"""


class ExportService:
    """Generates downloadable exports from completed coding sessions."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create_export(
        self,
        *,
        tenant_id: uuid.UUID,
        user_id: uuid.UUID,
        session_id: uuid.UUID,
        format: ExportFormat,
    ) -> Export:
        export = Export(
            tenant_id=tenant_id,
            session_id=session_id,
            user_id=user_id,
            format=format.value,
            status="pending",
        )
        self._session.add(export)
        await self._session.flush()
        return export

    async def get_export(
        self,
        export_id: uuid.UUID,
        tenant_id: uuid.UUID,
    ) -> Export | None:
        stmt = select(Export).where(
            Export.id == export_id,
            Export.tenant_id == tenant_id,
        )
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def generate_export(
        self,
        export_id: uuid.UUID,
        tenant_id: uuid.UUID,
        include_reasoning: bool = True,
        include_clinical_notes: bool = True,
    ) -> Export:
        """Generate the export file and update the export record."""
        export = await self.get_export(export_id, tenant_id)
        if export is None:
            raise ValueError(f"Export {export_id} not found")

        export.status = "processing"
        await self._session.flush()

        session = await self._fetch_session(export.session_id, tenant_id)
        if session is None:
            export.status = "error"
            export.error_message = "Coding session not found"
            await self._session.flush()
            raise ValueError("Coding session not found")

        patient = None
        if session.patient_id:
            patient = await self._fetch_patient(session.patient_id, tenant_id)

        results = list(session.results) if session.results else []

        _EXPORT_DIR.mkdir(parents=True, exist_ok=True)
        file_path: Path

        try:
            fmt = ExportFormat(export.format)
            if fmt == ExportFormat.PDF:
                file_path = await self._generate_pdf(
                    session, results, patient,
                    include_reasoning=include_reasoning,
                    include_clinical_notes=include_clinical_notes,
                )
            elif fmt == ExportFormat.CSV:
                file_path = await self._generate_csv(session, results, patient)
            elif fmt == ExportFormat.JSON:
                file_path = await self._generate_json(session, results, patient)
            elif fmt == ExportFormat.HL7:
                file_path = await self._generate_hl7(session, results, patient)
            else:
                raise ValueError(f"Unsupported format: {export.format}")

            export.status = "completed"
            export.file_path = str(file_path)
            export.file_size = file_path.stat().st_size
            export.completed_at = datetime.now(timezone.utc)

        except Exception as exc:
            export.status = "error"
            export.error_message = str(exc)[:1024]
            logger.exception("Export generation failed for %s", export_id)
            raise
        finally:
            await self._session.flush()

        return export

    async def _fetch_session(
        self, session_id: uuid.UUID, tenant_id: uuid.UUID
    ) -> CodingSession | None:
        stmt = select(CodingSession).where(
            CodingSession.id == session_id,
            CodingSession.tenant_id == tenant_id,
        )
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def _fetch_patient(
        self, patient_id: uuid.UUID, tenant_id: uuid.UUID
    ) -> Patient | None:
        stmt = select(Patient).where(
            Patient.id == patient_id,
            Patient.tenant_id == tenant_id,
        )
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def _generate_pdf(
        self,
        session: CodingSession,
        results: list[CodingResult],
        patient: Patient | None,
        include_reasoning: bool = True,
        include_clinical_notes: bool = True,
    ) -> Path:
        template = Template(_PDF_TEMPLATE)
        html = template.render(
            session=session,
            results=sorted(results, key=lambda r: r.sequence_order),
            patient=patient,
            include_reasoning=include_reasoning,
            include_clinical_notes=include_clinical_notes,
            export_date=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        )

        from weasyprint import HTML

        file_path = _EXPORT_DIR / f"{session.id}.pdf"
        HTML(string=html).write_pdf(str(file_path))
        return file_path

    async def _generate_csv(
        self,
        session: CodingSession,
        results: list[CodingResult],
        patient: Patient | None,
    ) -> Path:
        file_path = _EXPORT_DIR / f"{session.id}.csv"

        with open(file_path, "w", newline="", encoding="utf-8-sig") as f:
            writer = csv.writer(f, quoting=csv.QUOTE_ALL)

            writer.writerow(["Export Date", datetime.now(timezone.utc).isoformat()])
            if patient:
                writer.writerow(["Patient Name", f"{patient.first_name} {patient.last_name}"])
                writer.writerow(["Date of Birth", str(patient.date_of_birth or "N/A")])
                writer.writerow(["MRN", patient.mrn])
                writer.writerow(["Gender", patient.gender or "N/A"])
            writer.writerow(["Session ID", str(session.id)])
            writer.writerow(["Encounter Date", session.created_at.isoformat()])
            writer.writerow(["Standard", "ICD-10-CM 2026"])
            writer.writerow([])

            writer.writerow([
                "Code", "Description", "Confidence", "Validated",
                "Primary", "Rationale", "Coding Instructions",
            ])

            for r in sorted(results, key=lambda x: x.sequence_order):
                writer.writerow([
                    r.icd_code,
                    r.icd_description,
                    f"{r.confidence_score:.2f}",
                    "Yes" if r.is_validated else "No",
                    "Yes" if r.is_primary else "No",
                    r.rationale or "",
                    r.coding_instructions or "",
                ])

        return file_path

    async def _generate_json(
        self,
        session: CodingSession,
        results: list[CodingResult],
        patient: Patient | None,
    ) -> Path:
        data = {
            "export_version": "1.0",
            "export_date": datetime.now(timezone.utc).isoformat(),
            "session_id": str(session.id),
            "standard": {
                "name": "ICD-10-CM",
                "version": "2026",
                "effective_date": "2026-04-01",
            },
            "patient": None,
            "encounter": {
                "date": session.created_at.isoformat(),
                "clinical_notes": session.clinical_input,
            },
            "codes": [],
        }

        if patient:
            data["patient"] = {
                "name": f"{patient.first_name} {patient.last_name}",
                "date_of_birth": str(patient.date_of_birth) if patient.date_of_birth else None,
                "mrn": patient.mrn,
                "gender": patient.gender,
            }

        for r in sorted(results, key=lambda x: x.sequence_order):
            data["codes"].append({
                "code": r.icd_code,
                "description": r.icd_description,
                "confidence": r.confidence_score,
                "is_validated": r.is_validated,
                "is_primary": r.is_primary,
                "rationale": r.rationale,
                "coding_instructions": r.coding_instructions,
                "seventh_char": r.seventh_char,
            })

        file_path = _EXPORT_DIR / f"{session.id}.json"
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        return file_path

    async def _generate_hl7(
        self,
        session: CodingSession,
        results: list[CodingResult],
        patient: Patient | None,
    ) -> Path:
        bundle: dict = {
            "resourceType": "Bundle",
            "type": "collection",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "entry": [],
        }

        patient_id = str(session.patient_id or uuid.uuid4())
        encounter_id = str(session.id)

        if patient:
            bundle["entry"].append({
                "resource": {
                    "resourceType": "Patient",
                    "id": patient_id,
                    "name": [{"given": [patient.first_name], "family": patient.last_name}],
                    "birthDate": str(patient.date_of_birth) if patient.date_of_birth else None,
                    "gender": (patient.gender or "unknown").lower(),
                    "identifier": [
                        {"type": {"text": "MRN"}, "value": patient.mrn}
                    ],
                }
            })

        bundle["entry"].append({
            "resource": {
                "resourceType": "Encounter",
                "id": encounter_id,
                "status": "finished",
                "class": {"code": "AMB", "display": "ambulatory"},
                "subject": {"reference": f"Patient/{patient_id}"},
                "period": {"start": session.created_at.isoformat()},
            }
        })

        for r in sorted(results, key=lambda x: x.sequence_order):
            bundle["entry"].append({
                "resource": {
                    "resourceType": "Condition",
                    "code": {
                        "coding": [
                            {
                                "system": "http://hl7.org/fhir/sid/icd-10-cm",
                                "code": r.icd_code,
                                "display": r.icd_description,
                            }
                        ]
                    },
                    "subject": {"reference": f"Patient/{patient_id}"},
                    "encounter": {"reference": f"Encounter/{encounter_id}"},
                    "recordedDate": session.created_at.strftime("%Y-%m-%d"),
                }
            })

        file_path = _EXPORT_DIR / f"{session.id}.fhir.json"
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(bundle, f, indent=2, ensure_ascii=False)
        return file_path
